config:
# others
    seed: 1234
    num_frames: 6
    mode: pixel
    offset_noise: true
    gd_type: xyz
# model related
    models:
        config: imagedream/configs/sd_v2_base_ipmv_chin8_zero_snr.yaml
        resume: models/xyz.pth

# eval related
    sampler:
        target: libs.sample.ImageDreamDiffusionStage2
        params:
            mode: pixel
            num_frames: 6
            camera_views: [1, 2, 3, 4, 5, 0]
            ref_position: null
            random_background: false
            offset_noise: true
            resize_rate: 1.0


